### ISSUE TITLE
question of CCA Layer and RSA Layer

### ISSUE THREAD

**Issue by kk6398** [njulj/RFDN#12]
In your code, the final layer of RFDB is RSA. But in your paper ,the final layer RFDB is CCA(same as the IMDN). Could you tell me why and explain the theory of it.    Looking forward your reply.

**Comment by scutlrr** [comment]
The code provided by the author is used in the competition and is mentioned at the end of the paper.

**Comment by Senwang98** [comment]
@kk6398 , see IMDN and replace ESA with CCA.
The author only provide AIM 2020 codes
