### ISSUE TITLE
distillation_rate is not used in class RFDB(nn.Module),how to change the distillation rate in the  experiment？

### ISSUE THREAD

**Issue by liuweiyy** [njulj/RFDN#2]

**Comment by njulj** [comment]
You can set the channel numbers of self.dc according to the distillation rate. In our code, we fixed the distillation rate at 0.5

**Comment by liuweiyy** [comment]
> You can set the channel numbers of self.dc according to the distillation rate. In our code, we fixed the distillation rate at 0.5

thank you
