### ISSUE TITLE
About the number of network parameters 

### ISSUE THREAD

**Issue by scutlrr** [njulj/RFDN#5]
I built the RFDN (x4) network as described in your paper, but its number of parameters is only 545K, which is less than the number of parameters in your paper (550K). Can you give me some tips?

**Comment by scutlrr** [comment]
I think I know where the problem is. The “reduction” in the CCA module should be 4 (however, it is 16 in IMDN).

**Comment by leftdoor** [comment]
I have the same question as you, and thank you for the reduction=4 that you mentioned above. Have you get the same result in this paper?

**Comment by leftdoor** [comment]
I got the answer from your another reply, thank u

**Comment by Lininggggggg** [comment]
> I built the RFDN (x4) network as described in your paper, but its number of parameters is only 545K, which is less than the number of parameters in your paper (550K). Can you give me some tips?

你好，想请问下一般写论文的时候，想对比和其他模型的效果图的话，那些模型的效果图是怎么得到的呢？
有公开的效果图库吗？还是说每个作者都需要重新跑一遍那些论文的模型，然后再附上论文的结果图吗？
那如果复现后没能达到论文的指标，直接附图上去不是会不公平吗？
请问您是怎么解决这个问题的呀？麻烦解答下，谢谢啊

**Comment by scutlrr** [comment]
> > I built the RFDN (x4) network as described in your paper, but its number of parameters is only 545K, which is less than the number of parameters in your paper (550K). Can you give me some tips?
> 
> 你好，想请问下一般写论文的时候，想对比和其他模型的效果图的话，那些模型的效果图是怎么得到的呢？
> 有公开的效果图库吗？还是说每个作者都需要重新跑一遍那些论文的模型，然后再附上论文的结果图吗？
> 那如果复现后没能达到论文的指标，直接附图上去不是会不公平吗？
> 请问您是怎么解决这个问题的呀？麻烦解答下，谢谢啊

通常都是把对比实验的代码重新跑一遍的，因为作者不提供对比实验的可视化数据。正常来说复现的结果都相差不大，有时候甚至会比论文中给出的指标更高（亲测，感觉可能为了凸显自己的指标故意放低对比实验的。。），当然如果你直接copy指标数据，然后自己复现得到可视化结果指不定也**（哈哈哈不建议）

**Comment by Lininggggggg** [comment]
这样，好的，谢谢了啊【抱拳】

**Comment by scutlrr** [comment]
@Lininggggggg 你的测试指标已经超过论文了吗-_-

**Comment by Lininggggggg** [comment]
没有哈哈哈，改了几个，参数量乘加数是低了很多，但dB值没能超过，set5x4上欠0.1多；
但老师赶着要了，就先写着吧
你呢，大佬

**Comment by scutlrr** [comment]
> 没有哈哈哈，改了几个，参数量乘加数是低了很多，但dB值没能超过，set5x4上欠0.1多；
> 但老师赶着要了，就先写着吧
> 你呢，大佬

之前就训练x2模型改几个模块  参数只有原来一半左右  指标最高37.97dB左右  之后有时间在研究研究。训练时间实在hold不住

**Comment by Lininggggggg** [comment]
> I built the RFDN (x4) network as described in your paper, but its number of parameters is only 545K, which is less than the number of parameters in your paper (550K). Can you give me some tips?

有个问题需要再请教下：我现在在x4上的参数量是改为和作者的一样的了，但我发现在x2上的参数量和x4的一样都是550K了，不是论文提到的534k，请问你知道怎么改吗？还是改reduction吗？

**Comment by scutlrr** [comment]
> > I built the RFDN (x4) network as described in your paper, but its number of parameters is only 545K, which is less than the number of parameters in your paper (550K). Can you give me some tips?
> 
> 有个问题需要再请教下：我现在在x4上的参数量是改为和作者的一样的了，但我发现在x2上的参数量和x4的一样都是550K了，不是论文提到的534k，请问你知道怎么改吗？还是改reduction吗？

模块的upscale改一下就好了  我改完x4的之后其他尺度参数量和论文都一样。

**Comment by Lininggggggg** [comment]
确实啊，忘记改了，谢谢谢谢！

**Comment by Doreenqiuyue** [comment]
> I have the same question as you, and thank you for the reduction=4 that you mentioned above. Have you get the same result in this paper?

Hello, where is the setting of 'reduction' ? Thank you!

**Comment by raychl94** [comment]
> > I have the same question as you, and thank you for the reduction=4 that you mentioned above. Have you get the same result in this paper?
> 
> Hello, where is the setting of 'reduction' ? Thank you!

hello,Have you solved the problem?
